config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => "home#index"
  
  match 'ping', to: 'home#ping', via: [:get]
  match "/:controller/:id/:action", via: [:get, :post]
  
  resources :tvshows
  
  match "*path", :controller => "application", :action => "not_found", via: [:get, :post]

end

app/models/tvshow.rb
class Tvshow < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :user_id, :title, :episode
  # attr_accessible :user_id, :title, :episode, :ongoing, :date
  
  def change(option, params)
    if self.user_id != params[:user_id]
      false
    elsif option == 'next'
      update_attributes(episode: self.episode.next, date: Time.now)
    elsif option == 'completed'
      update_attributes(ongoing: false)
    else
      update_attributes(params.merge(date: Time.now))
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :tvshows

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me

  DEFAULT_SORT_VALUES = [
    'title',
    'title+desc',
    'episode',
    'episode+desc',
    'date',
    'date+desc'
  ]

  def ongoing_tv_shows(sort: 'title')
    tvshows.where(ongoing: true).order(sort)
  end

  def completed_tv_shows(sort: 'title')
    tvshows.where(ongoing: false).order(sort)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def not_found
    render :template => 'pages/404', :status => :not_found
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to "/tvshows"
    end
  end

  def ping
    render :layout => false
  end

end

app/controllers/tvshows_controller.rb
class TvshowsController < ApplicationController
  before_filter :require_login
  
  def require_login
    unless user_signed_in?
      # flash[:error] = "You must be logged in to access this section"
      redirect_to "/users/sign_in"
    end
  end

  def index
    @ongoing = current_user.ongoing_tv_shows(sort: params[:sort].presence || current_user.default_sort)
    @completed = current_user.completed_tv_shows(sort: params[:sort].presence || current_user.default_sort)
  end

  def show
    @tvshow = Tvshow.find_by_id(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @tvshow }
    end
  end

  def new
  end

  def edit
  end

  def create
    @tvshow = Tvshow.new(tvshow_params.merge(user_id: current_user.id))

    if @tvshow.save
      result = @tvshow.reload.attributes.except('user_id')
      result['date'] = result['date'].strftime("%B %d, %Y")
    else
      Rails.logger.warn("didn't save correctly")
      # TODO: make a failure result
      # # format.json { render :json => @tvshow.errors, :status => :unprocessable_entity }
    end

    render :json => result
  end

  def change
    @tvshow = Tvshow.find_by_id(params[:id])

    if @tvshow.change(params[:option], {user_id: current_user.id})
      result = @tvshow.reload.attributes.except('user_id')
      result['date'] = result['date'].strftime("%B %d, %Y")
    else
      Rails.logger.warn("didn't save correctly")
      # TODO: make a failure result
      # # format.json { render :json => @tvshow.errors, :status => :unprocessable_entity }
    end

    render :json => result
  end

  def update
    @tvshow = Tvshow.find_by_id(params[:id])

    if @tvshow.change('update', tvshow_params.merge(user_id: current_user.id))
      result = @tvshow.reload.attributes.except('user_id')
      result['date'] = result['date'].strftime("%B %d, %Y")
    else
      Rails.logger.warn("didn't save correctly")
      # TODO: make a failure result
      # # format.json { render :json => @tvshow.errors, :status => :unprocessable_entity }
    end

    render :json => result
  end

  def destroy
    @tvshow = Tvshow.find_by_id(params[:id])
    @tvshow.destroy

    respond_to do |format|
      format.html { redirect_to tvshows_url }
      format.json { head :ok }
    end
  end

  private

  def tvshow_params
    params.require(:tvshow).permit(:title, :episode, :ongoing, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tvshows_helper.rb
module TvshowsHelper
end

app/views/home/index.html.haml
%h1.text_center Welcome to a TV Series Episode Management Site
%p.text_left
  This site is intended to be used to keep track of TV series one watches and the current episode that
  hasn't been watched corresponding to that particular TV series. Newly added TV series start off at
  episode 1, but may be edited and changed (on creation or any time afterwards) to another episode
  number. Episodes can be easily managed with a single click to advance the episode counter to the next
  episode, after the current episode has been watched. Completed TV series will be moved to a separate
  list, which can be displayed on request, to review older TV series one has watched in the past.

app/views/home/ping.html.haml
pong

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TV Show Listings
    = javascript_include_tag "application", 'bootstrap', 'cookie', 'underscore-min'
    = stylesheet_link_tag    "application"
    = csrf_meta_tags
  %body
    %div{:id => "top_notice hidden"}
      %p.notice.hidden= notice
      %p.alert.hidden= alert

    %nav.navbar.navbar-inverse
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          - if user_signed_in?
            = link_to "TV Show List", tvshows_path, :class => 'navbar-brand'
          - else
            = link_to "TV Shows", root_path, :class => 'navbar-brand'
        .collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              - if user_signed_in?
                %li.dropdown
                  %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                    Account
                    %span.caret
                  %ul.dropdown-menu{:role => "menu"}
                    %li= link_to('Settings', edit_user_registration_path)
                    %li= link_to('Logout', destroy_user_session_path, :method => :delete)
              - else
                %li= link_to('Register', new_user_registration_path)
                %li= link_to('Login', new_user_session_path)
    .container
      = yield

app/views/pages/404.html.haml
%div{:style => "margin:40px auto;width:500px;"}
  %h1 You've reached this page in error.
  %p Redirecting you in 5 seconds.
#type.hidden
  - if user_signed_in?
    TRUE
  - else
    FALSE
:javascript
  var timer;
  function redirect() {
  	if ($("#type").text() == "TRUE")
  		window.location.href = "/";
  	else
  		window.location.href = "/tvshows"
  };
  $(document).ready(function() {
  	timer = setTimeout("redirect()", 5000);
  });
  

app/views/tvshows/_form.html.haml
= form_for @tvshow=Tvshow.new, :html => {:class => 'form-inline'} do |f|
  #tvshow_form_modal.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'tvshow_form_label', :role => 'dialog', :tabindex => '-1', data: {action: 'new'}}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} &times;
          %h4#tvshow_form_label.modal-title Add TV Series
        .modal-body
          - if @tvshow.errors.any?
            #error_explanation
              %h2
                = pluralize(@tvshow.errors.count, "error")
                prohibited this tvshow from being saved:
              %ul
                - @tvshow.errors.full_messages.each do |msg|
                  %li= msg

          .field
            = f.label :title
            = f.text_field :title
          .field
            = f.label :episode
            = f.number_field :episode
          .field
            = f.check_box :ongoing
            = f.label :ongoing
          = f.hidden_field :date, :value => Time.now
        .modal-footer
          %button.btn.btn-default{'data-dismiss' => 'modal', type: 'button'} Close
          %button#submit.btn.btn-primary{type: 'submit'} Add/Edit TV Series

app/views/tvshows/_show_tvshow.html.haml
%div{id: ul_id, class: (ul_id.index('completed') ? 'hidden' : '')}
  .row
    .col-xs-12.col-sm-5.col-md-6.col-lg-6.text-center
      - if params[:sort] != "title"
        = link_to "Title", :sort => "title"
      - else
        = link_to "Title", :sort => "title desc"
    .col-xs-12.col-sm-2.col-md-2.col-lg-2.text-center
      - if params[:sort] != "episode"
        = link_to "Episode", :sort => "episode"
      - else
        = link_to "Episode", :sort => "episode desc"
    .col-xs-12.col-sm-2.col-md-2.col-lg-2.text-center
      - if params[:sort] != "date"
        = link_to "Date", :sort => "date"
      - else
        = link_to "Date", :sort => "date desc"
    .col-xs-12.col-sm-3.col-md-2.col-lg-2.text-center
      Menu

  .row
    &nbsp;

  - if "#{ul_id}" == "ongoing_tvshow" && tvshow.length > 1
    .border-bottom
      .row
        .col-xs-12.col-sm-12.col-md-12.col-lg-12
          .pull-right
            %a.new{:href => "#", :title => "New TV Series"} Add New Series

  - tvshow.each_with_index do |series, index|
    %div{class: (index + 1) != tvshow.count ? 'border-bottom entry' : 'entry'}
      .row{data: {id: series.id, title: series.title, episode: series.episode, ongoing: (!!series.ongoing ? 1 : 0)}}
        .title.col-xs-12.col-sm-5.col-md-6.col-lg-6= series.title
        .episode.col-xs-6.col-sm-2.col-md-2.col-lg-2.text-center= series.episode
        - if current_user.time_zone.present?
          .date.col-xs-6.col-sm-2.col-md-2.col-lg-2.text-center= (series.date + ActiveSupport::TimeZone.new(current_user.time_zone).now.utc_offset).strftime("%B %d, %Y")
        - else
          .date.col-xs-6.col-sm-2.col-md-2.col-lg-2.text-center= series.date.strftime("%B %d, %Y")
        .col-xs-12.col-sm-3.col-md-2.col-lg-2
          .pull-right
            - if "#{ul_id}" == "ongoing_tvshow"
              %a.next{:href => '#', action: "/tvshows/#{series.id}/change?option=next"} Next
              &nbsp;|&nbsp;
              %a.edit{:href => '#', action: "/tvshows/#{series.id}"} Edit
              &nbsp;|&nbsp;
              #{link_to "Delete", series, :confirm => 'Are you sure?', :method => :delete}
            - else
              Next
              &nbsp;|&nbsp;
              %a.edit{:href => '#', action: "/tvshows/#{series.id}"} Edit
              &nbsp;|&nbsp;
              Delete

  - if "#{ul_id}" == "ongoing_tvshow"
    .border-top
      .row
        .col-xs-12.col-sm-12.col-md-12.col-lg-12
          .pull-right
            %a.new{:href => "#", :title => "New TV Series"} Add New Series

app/views/tvshows/edit.html.haml
= render 'form', :submit_label => 'Edit TV Series'

app/views/tvshows/index.html.haml
%a#ongoing{:href => "#"} [ - ] ONGOING TV SHOW
= render 'show_tvshow', :ul_id => "ongoing_tvshow", :tvshow => @ongoing

%br

%a#completed{:href => "#"} [ + ] COMPLETED TV SHOW
= render 'show_tvshow', :ul_id => "completed_tvshow", :tvshow => @completed

%br
%br

= render 'form'

:javascript
  var toggle = "-";

  $(document).ready(function(){
    var ongoing_var = $.cookie("ongoing");
    var completed_var = $.cookie("completed");

    if (ongoing_var == "hide")
      $("#ongoing").click();
    if (completed_var == "show")
      $("#completed").click();

    setInterval(ping, 300000);
  });

  function ping(){
    $.ajax({url: '/ping'});
  }

  $("#ongoing").click(function(){
    if ($(this).html() == "[ - ] ONGOING TV SHOW"){
      $(this).html("[ + ] ONGOING TV SHOW");
      $("#ongoing_tvshow").addClass('hidden');
      $.cookie("ongoing", "hide");
    } else {
      $(this).html("[ - ] ONGOING TV SHOW");
      $("#ongoing_tvshow").removeClass('hidden');
      $.cookie("ongoing", "show");
    }

    return false;
  });

  $("#completed").click(function(){
    if ($(this).html() == "[ - ] COMPLETED TV SHOW"){
      $(this).html("[ + ] COMPLETED TV SHOW");
      $("#completed_tvshow").addClass('hidden');
      $.cookie("completed", "hide");
    } else {
      $(this).html("[ - ] COMPLETED TV SHOW");
      $("#completed_tvshow").removeClass('hidden');
      $.cookie("completed", "show");
    }

    return false;
  });

  $(document).on("click", ".edit, .new", function(){
    if ( $(this).attr("class") == "new" ){
      // clear modal and form data
      $('#tvshow_form_modal').data('action', 'new');
      $('form').attr('action', '/tvshows');

      $('.modal-title').html('Add TV Series');
      $('#tvshow_title').val('');
      $('#tvshow_episode').val(1);
      $('#tvshow_ongoing').prop('checked', true);
      $('#tvshow_form_modal #submit').text('Submit');

      $('#tvshow_form_modal').modal('show');
    } else {
      // set modal and form data
      var series = $(this).closest('.row').data();

      $('#tvshow_form_modal').data('action', 'edit');
      $('form').attr('action', $(this).attr('action'));

      $('.modal-title').html(series.title);
      $('#tvshow_title').val(series.title);
      $('#tvshow_episode').val(series.episode);
      $('#tvshow_ongoing').prop('checked', series.ongoing);
      $('#tvshow_form_modal #submit').text('Confirm');

      $('#tvshow_form_modal').modal('show');
    }

    return false;
  });

  $('#tvshow_form_modal').on('shown.bs.modal', function (){
    if ($('#tvshow_form_modal').data('action') == 'new'){
      $('#tvshow_title').focus();
    } else {
      $('#tvshow_episode').select();
    }
  });

  $('#tvshow_form_modal').on('hidden.bs.modal', function (){
    if ($('#tvshow_form_modal').data('action') == 'new'){
      $('#tvshow_title').blur();
    } else {
      $('#tvshow_episode').replaceWith($('#tvshow_episode')[0].outerHTML);
    }
  });

  $('form').on('submit', function(){
    var action = $(this).attr('action');
    var params = $("form").serialize();
    if ($('#tvshow_form_modal').data('action') == 'edit'){
      var params = params + '&' + $.param({ _method: 'patch' });
    }
    submitData(action, params, function(data){
      $('#tvshow_form_modal').modal('hide');
      updateData(JSON.parse(data));
    });

    return false;
  });

  $('.next, .completed').on('click', function(){
    var action = $(this).attr('action');
    submitData(action, {}, function(data){
      updateData(JSON.parse(data));
    });

    return false;
  });

  function submitData(action, params, callback){
    $.ajax({
      url: action,
      method: 'POST',
      data: params,
      dataType: "html"
    }).done(callback);

    return false;
  }

  function updateData(data){
    var row = $('.row[data-id='+data.id+']')

    // reload if the changed data probably needs to be resorted
    if (row.data('title') != data.title || row.data('ongoing') != data.ongoing){
      location.reload(); 
    }

    _.each(data, function(v,k){
      if (row.data(k) != v){
        row.data(k,v)
        row.find('.'+k).fadeOut('slow', function(){
          $(this).text(v).fadeIn('slow');
        })
      }
    });
  }

app/views/tvshows/new.html.haml
= render 'form', :submit_label => 'Add TV Series'

app/views/tvshows/show.html.haml
%p#notice= notice
%p
  %b Title:
  = @tvshow.title
%p
  %b Episode:
  = @tvshow.episode
%p
  %b Ongoing:
  = @tvshow.ongoing
= link_to 'Edit', edit_tvshow_path(@tvshow)
|
\#{link_to 'Back', tvshows_path}